## sets the bind port
server.port: 8091

## logging configuration
server.tomcat:
  accessLogEnabled: true
  accessLogPattern: "%a asdasd"

## kafka configuration
spring.cloud.stream.bindings.output.destination: json-waypoint

## disable auth on /beans
endpoints.beans.sensitive: false
