## sets the bind port
server.port: 8090

## sets the batch size
batch-sink.batch-size: 3
batch-sink.upload-endpoint: http://localhost:8090/upload

## enables request logging
server.tomcat.accessLogEnabled: true
server.tomcat.accessLogPattern: "%a asdasd"

## kafka configuration
spring.cloud.stream.bindings.input.destination: widget-topic
