
## disable http listener
spring.main.web-environment: false

## logging configuration
server.tomcat:
  accessLogEnabled: true
  accessLogPattern: "%a asdasd"

## kafka configuration
spring.cloud.stream.bindings.output.destination: some-topic

## disable auth on /beans
endpoints.beans.sensitive: false
