## sets the bind port
server.port: 8092

## sets the batch size
http-api-sink.batch-size: 3
http-api-sink.upload-endpoint: http://localhost:8090/upload

## enables request logging
server.tomcat.accessLogEnabled: true
server.tomcat.accessLogPattern: "%a asdasd"

## kafka configuration
spring.cloud.stream.bindings.input.destination: widget-topic
